/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GatedRouteRouteImport } from './routes/_gated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as GatedAdminRouteImport } from './routes/_gated/admin'
import { Route as GatedAdminLegacyRouteImport } from './routes/_gated/admin-legacy'
import { Route as GatedAnalyticsRouteImport } from './routes/_gated/analytics'
import { Route as GatedApiPanelRouteImport } from './routes/_gated/api-panel'
import { Route as GatedDiagnosticsRouteImport } from './routes/_gated/diagnostics'
import { Route as WorkSlugRouteImport } from './routes/work.$slug'
import { Route as ApiPublicAdblockDiagnosticsRouteImport } from './routes/api/public/adblock-diagnostics'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GatedRouteRoute = GatedRouteRouteImport.update({
  id: '/_gated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const GatedAdminRoute = GatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => GatedRouteRoute,
} as any)
const GatedAdminLegacyRoute = GatedAdminLegacyRouteImport.update({
  id: '/admin-legacy',
  path: '/admin-legacy',
  getParentRoute: () => GatedRouteRoute,
} as any)
const GatedAnalyticsRoute = GatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => GatedRouteRoute,
} as any)
const GatedApiPanelRoute = GatedApiPanelRouteImport.update({
  id: '/api-panel',
  path: '/api-panel',
  getParentRoute: () => GatedRouteRoute,
} as any)
const GatedDiagnosticsRoute = GatedDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => GatedRouteRoute,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdblockDiagnosticsRoute =
  ApiPublicAdblockDiagnosticsRouteImport.update({
    id: '/api/public/adblock-diagnostics',
    path: '/api/public/adblock-diagnostics',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unlock': typeof UnlockRoute
  '/admin': typeof GatedAdminRoute
  '/admin-legacy': typeof GatedAdminLegacyRoute
  '/analytics': typeof GatedAnalyticsRoute
  '/api-panel': typeof GatedApiPanelRoute
  '/diagnostics': typeof GatedDiagnosticsRoute
  '/work/$slug': typeof WorkSlugRoute
  '/api/public/adblock-diagnostics': typeof ApiPublicAdblockDiagnosticsRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unlock': typeof UnlockRoute
  '/admin': typeof GatedAdminRoute
  '/admin-legacy': typeof GatedAdminLegacyRoute
  '/analytics': typeof GatedAnalyticsRoute
  '/api-panel': typeof GatedApiPanelRoute
  '/diagnostics': typeof GatedDiagnosticsRoute
  '/work/$slug': typeof WorkSlugRoute
  '/api/public/adblock-diagnostics': typeof ApiPublicAdblockDiagnosticsRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_gated': typeof GatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unlock': typeof UnlockRoute
  '/_gated/admin': typeof GatedAdminRoute
  '/_gated/admin-legacy': typeof GatedAdminLegacyRoute
  '/_gated/analytics': typeof GatedAnalyticsRoute
  '/_gated/api-panel': typeof GatedApiPanelRoute
  '/_gated/diagnostics': typeof GatedDiagnosticsRoute
  '/work/$slug': typeof WorkSlugRoute
  '/api/public/adblock-diagnostics': typeof ApiPublicAdblockDiagnosticsRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/terms'
    | '/unlock'
    | '/admin'
    | '/admin-legacy'
    | '/analytics'
    | '/api-panel'
    | '/diagnostics'
    | '/work/$slug'
    | '/api/public/adblock-diagnostics'
    | '/api/public/health'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/terms'
    | '/unlock'
    | '/admin'
    | '/admin-legacy'
    | '/analytics'
    | '/api-panel'
    | '/diagnostics'
    | '/work/$slug'
    | '/api/public/adblock-diagnostics'
    | '/api/public/health'
  id:
    | '__root__'
    | '/'
    | '/_gated'
    | '/auth'
    | '/sitemap.xml'
    | '/terms'
    | '/unlock'
    | '/_gated/admin'
    | '/_gated/admin-legacy'
    | '/_gated/analytics'
    | '/_gated/api-panel'
    | '/_gated/diagnostics'
    | '/work/$slug'
    | '/api/public/adblock-diagnostics'
    | '/api/public/health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GatedRouteRoute: typeof GatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  UnlockRoute: typeof UnlockRoute
  WorkSlugRoute: typeof WorkSlugRoute
  ApiPublicAdblockDiagnosticsRoute: typeof ApiPublicAdblockDiagnosticsRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_gated': {
      id: '/_gated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_gated/admin': {
      id: '/_gated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof GatedAdminRouteImport
      parentRoute: typeof GatedRouteRoute
    }
    '/_gated/admin-legacy': {
      id: '/_gated/admin-legacy'
      path: '/admin-legacy'
      fullPath: '/admin-legacy'
      preLoaderRoute: typeof GatedAdminLegacyRouteImport
      parentRoute: typeof GatedRouteRoute
    }
    '/_gated/analytics': {
      id: '/_gated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof GatedAnalyticsRouteImport
      parentRoute: typeof GatedRouteRoute
    }
    '/_gated/api-panel': {
      id: '/_gated/api-panel'
      path: '/api-panel'
      fullPath: '/api-panel'
      preLoaderRoute: typeof GatedApiPanelRouteImport
      parentRoute: typeof GatedRouteRoute
    }
    '/_gated/diagnostics': {
      id: '/_gated/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof GatedDiagnosticsRouteImport
      parentRoute: typeof GatedRouteRoute
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/adblock-diagnostics': {
      id: '/api/public/adblock-diagnostics'
      path: '/api/public/adblock-diagnostics'
      fullPath: '/api/public/adblock-diagnostics'
      preLoaderRoute: typeof ApiPublicAdblockDiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GatedRouteRouteChildren {
  GatedAdminRoute: typeof GatedAdminRoute
  GatedAdminLegacyRoute: typeof GatedAdminLegacyRoute
  GatedAnalyticsRoute: typeof GatedAnalyticsRoute
  GatedApiPanelRoute: typeof GatedApiPanelRoute
  GatedDiagnosticsRoute: typeof GatedDiagnosticsRoute
}

const GatedRouteRouteChildren: GatedRouteRouteChildren = {
  GatedAdminRoute: GatedAdminRoute,
  GatedAdminLegacyRoute: GatedAdminLegacyRoute,
  GatedAnalyticsRoute: GatedAnalyticsRoute,
  GatedApiPanelRoute: GatedApiPanelRoute,
  GatedDiagnosticsRoute: GatedDiagnosticsRoute,
}

const GatedRouteRouteWithChildren = GatedRouteRoute._addFileChildren(
  GatedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GatedRouteRoute: GatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  UnlockRoute: UnlockRoute,
  WorkSlugRoute: WorkSlugRoute,
  ApiPublicAdblockDiagnosticsRoute: ApiPublicAdblockDiagnosticsRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
