/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as GatedRouteRouteImport } from './routes/_gated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GatedApiPanelRouteImport } from './routes/_gated/api-panel'
import { Route as GatedAnalyticsRouteImport } from './routes/_gated/analytics'
import { Route as GatedAdminRouteImport } from './routes/_gated/admin'
import { Route as ApiPublicAdblockDiagnosticsRouteImport } from './routes/api/public/adblock-diagnostics'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const GatedRouteRoute = GatedRouteRouteImport.update({
  id: '/_gated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GatedApiPanelRoute = GatedApiPanelRouteImport.update({
  id: '/api-panel',
  path: '/api-panel',
  getParentRoute: () => GatedRouteRoute,
} as any)
const GatedAnalyticsRoute = GatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => GatedRouteRoute,
} as any)
const GatedAdminRoute = GatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => GatedRouteRoute,
} as any)
const ApiPublicAdblockDiagnosticsRoute =
  ApiPublicAdblockDiagnosticsRouteImport.update({
    id: '/api/public/adblock-diagnostics',
    path: '/api/public/adblock-diagnostics',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof GatedAdminRoute
  '/analytics': typeof GatedAnalyticsRoute
  '/api-panel': typeof GatedApiPanelRoute
  '/api/public/adblock-diagnostics': typeof ApiPublicAdblockDiagnosticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof GatedAdminRoute
  '/analytics': typeof GatedAnalyticsRoute
  '/api-panel': typeof GatedApiPanelRoute
  '/api/public/adblock-diagnostics': typeof ApiPublicAdblockDiagnosticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_gated': typeof GatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_gated/admin': typeof GatedAdminRoute
  '/_gated/analytics': typeof GatedAnalyticsRoute
  '/_gated/api-panel': typeof GatedApiPanelRoute
  '/api/public/adblock-diagnostics': typeof ApiPublicAdblockDiagnosticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/analytics'
    | '/api-panel'
    | '/api/public/adblock-diagnostics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/analytics'
    | '/api-panel'
    | '/api/public/adblock-diagnostics'
  id:
    | '__root__'
    | '/'
    | '/_gated'
    | '/auth'
    | '/sitemap.xml'
    | '/terms'
    | '/_gated/admin'
    | '/_gated/analytics'
    | '/_gated/api-panel'
    | '/api/public/adblock-diagnostics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GatedRouteRoute: typeof GatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ApiPublicAdblockDiagnosticsRoute: typeof ApiPublicAdblockDiagnosticsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_gated': {
      id: '/_gated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_gated/api-panel': {
      id: '/_gated/api-panel'
      path: '/api-panel'
      fullPath: '/api-panel'
      preLoaderRoute: typeof GatedApiPanelRouteImport
      parentRoute: typeof GatedRouteRoute
    }
    '/_gated/analytics': {
      id: '/_gated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof GatedAnalyticsRouteImport
      parentRoute: typeof GatedRouteRoute
    }
    '/_gated/admin': {
      id: '/_gated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof GatedAdminRouteImport
      parentRoute: typeof GatedRouteRoute
    }
    '/api/public/adblock-diagnostics': {
      id: '/api/public/adblock-diagnostics'
      path: '/api/public/adblock-diagnostics'
      fullPath: '/api/public/adblock-diagnostics'
      preLoaderRoute: typeof ApiPublicAdblockDiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GatedRouteRouteChildren {
  GatedAdminRoute: typeof GatedAdminRoute
  GatedAnalyticsRoute: typeof GatedAnalyticsRoute
  GatedApiPanelRoute: typeof GatedApiPanelRoute
}

const GatedRouteRouteChildren: GatedRouteRouteChildren = {
  GatedAdminRoute: GatedAdminRoute,
  GatedAnalyticsRoute: GatedAnalyticsRoute,
  GatedApiPanelRoute: GatedApiPanelRoute,
}

const GatedRouteRouteWithChildren = GatedRouteRoute._addFileChildren(
  GatedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GatedRouteRoute: GatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiPublicAdblockDiagnosticsRoute: ApiPublicAdblockDiagnosticsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
